{% set version = "0.4.1" %}

package:
  name: pygmo_plugins_nonfree
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo_plugins_nonfree/archive/v{{ version }}.tar.gz
  sha256: 7feba14ce01ab3fc01434fc7ff976da44b3d46a78b671939fa6ef664ba0c9c50

build:
  number: 1
  skip: true  # [(win and py<36) or win32]

requirements:
  build:
    - toolchain
    - cmake
    - pagmo     2.6
    - pygmo     2.6
    - boost     1.66.0
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python
  run:
    - pagmo     2.6
    - pygmo     2.6
    - boost     1.66.0
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python

about:
  home: https://github.com/esa/pagmo_plugins_nonfree/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A package affiliated to pagmo/pygmo and providing additional solvers in the form of plugins (i.e. loading the third party libraries at run time)'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
