{% set version = "0.20" %}

package:
  name: pygmo_plugins_nonfree
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo_plugins_nonfree/archive/v{{ version }}.tar.gz
  sha256: 92e5b14db2dd10bbd03b389243124dfb9b7551789206461b871d8a5dec086528

build:
  number: 0
  skip: true  # [py<35]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - vs2017_{{ target_platform  }}    # [win]
  host:
    - pagmo-devel
    - pygmo     
    - numpy    
    - python
  run:
    - pagmo
    - pygmo   
    - python

about:
  home: https://github.com/esa/pagmo_plugins_nonfree/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A package affiliated to pagmo/pygmo and providing additional solvers in the form of plugins (i.e. loading the third party libraries at run time)'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo