{% set version = "0.8" %}

package:
  name: pygmo_plugins_nonfree
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo_plugins_nonfree/archive/v{{ version }}.tar.gz
  sha256: 3642f45bf9a4e8acb30636e995340c0d33f6d4b6428c9e27e3ff37a071536254

build:
  number: 0
  skip: true  # [(win and py<36) or win32]

requirements:
  build:
    - toolchain
    - cmake
    - pagmo     2.6
    - pygmo     2.6
    - boost     1.66.0
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python
  run:
    - pagmo     2.6
    - pygmo     2.6
    - boost     1.66.0
    - numpy     x.x
    - cloudpickle
    - ipyparallel
    - python

about:
  home: https://github.com/esa/pagmo_plugins_nonfree/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A package affiliated to pagmo/pygmo and providing additional solvers in the form of plugins (i.e. loading the third party libraries at run time)'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
