{% set version = "0.20" %}

package:
  name: pygmo_plugins_nonfree
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo_plugins_nonfree/archive/v{{ version }}.tar.gz
  sha256: 92e5b14db2dd10bbd03b389243124dfb9b7551789206461b871d8a5dec086528

build:
  number: 0
  skip: true  # [(win and py<36) or win32]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pagmo
    - pygmo
    - python
    - numpy
  run:
    - pagmo
    - pygmo
    - boost
    - {{ pin_compatible('numpy') }}
    - cloudpickle
    - ipyparallel
    - python

about:
  home: https://github.com/esa/pagmo_plugins_nonfree/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: A package affiliated to pagmo/pygmo and providing additional solvers in the form of plugins (i.e. loading the third party libraries at run time)

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
