{% set version = "0.24" %}

package:
  name: pygmo_plugins_nonfree
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo_plugins_nonfree/archive/v{{ version }}.tar.gz
  sha256: 4d54608942dac8cfc83519803f5c14a10993138f0dca06944a44a2b5f7e631a4
  patches:
    - boost_dll.diff

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make       # [unix]
  host:
    - python
    - pybind11
    - pybind11-abi
    - pagmo-devel
    - boost-cpp
  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
    - numpy
    - pygmo
    - python

about:
  home: https://github.com/esa/pagmo_plugins_nonfree/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: A package affiliated to pagmo/pygmo and providing additional solvers in the form of plugins (i.e. loading the third party libraries at run time)

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
