{% set version = "0.21" %}

package:
  name: pygmo_plugins_nonfree
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo_plugins_nonfree/archive/v{{ version }}.tar.gz
  sha256: 50dc3c2cf6484d45335c0dc0158a56281bdf567394652940498e9fb0cbad439f

build:
  number: 0
  skip: true  # [py<35]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - vs2017_{{ target_platform  }}    # [win]
  host:
    - pagmo-devel
    - pygmo
    - numpy
    - python
  run:
    - pygmo
    - python

about:
  home: https://github.com/esa/pagmo_plugins_nonfree/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: A package affiliated to pagmo/pygmo and providing additional solvers in the form of plugins (i.e. loading the third party libraries at run time)

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
