{% set version = "0.26" %}

package:
  name: pygmo_plugins_nonfree
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo_plugins_nonfree/archive/v{{ version }}.tar.gz
  sha256: 3113c3b6b15d9f2181c52750ccc77f942b4d2150fc62683207587141993d4a52
  patches:
    - add_pagmo.diff

build:
  number: 6
  ignore_run_exports:
    # pagmo-devel will automatically
    # put nlopt and ipopt as run dependencies,
    # but we don't actually need any symbol
    # from these libraries in pygmo's module.
    # Thus, remove them from the runtime
    # requirements.
    - nlopt
    - ipopt

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=2.10                        # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - make       # [unix]
  host:
    - python
    - pybind11 >=2.10
    - pybind11-abi
    - pagmo-devel =2.19.*
    - libboost-devel
  run:
    - numpy
    - pygmo
    - python

about:
  home: https://github.com/esa/pagmo_plugins_nonfree/
  license: GPL-3.0-or-later OR LGPL-3.0-or-later
  license_file: COPYING.lgpl3 
  summary: A package affiliated to pagmo/pygmo and providing additional solvers in the form of plugins (i.e. loading the third party libraries at run time)

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
