travis:
  secure:
    BINSTAR_TOKEN: TDv92Olnkwu/FwinKNi1PzL03PzRjTAK4sCJceEaz0kamqQjH3k5hGtzV7OOkYkAsIHXbF7USoWNTITcE+Tt3CSDrsZDOC8QygVJJKBJ6EhkDkMf0Ce/5n+yIJN+mMHxalR230bdWfStvWATmd4NBu16qKnCAXomBVWo2h0OisochueRSz9F5Uc5dGRu6//CB5cFXU7paKUrMWH0KdLTNeglLI9OI94mEmazzIkTD/dIapLE2dqkdetBJhUqrSa739t+Frc89EnxQQ8dXoEmXLiLxIYTWZm7o3gT51cxjGH3b3PhBy3rYMf0ehbVrFaFDJZxisDaXX//FwOnhUgxxNI7rC9daH8Gqlk6/lxWEheR5m7wANpSAb8wIyBQBoOoXG2Ut6ntPN38Kg1+YTjZURKJJHeRFxUL/coeDWdOQ9kr8Gz92k3Dc1TSFxp1w/axX6xymQxVr0HwXCN75x4eP0Sh7axeS/YN1VtSMqNPOAaObJqXFgNVTSkhyJ7eeTQpru/pQ/grMvT/DscKU+7BnZvap7GZst2Y9St7g31Y2AmF5St/FrA9guhqyxyLMchHQvzTWCt6PfXNsy69nnIp8XYgQJMBCPJ2XWrAlH4COFAHp5FyklDqodpEWqyTdOzHDU/qeYKLIfQAwYImIw+QnIOkXHx+4mRrGPUGTVbJYl4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
