travis:
  secure:
    BINSTAR_TOKEN: FnpqPUncNhENR2BhNoEEIw5nE9uSTcNps5rvUs6BOvivxUJLiFKGIx8CQ5beNJuWTEOMBNabV4uQK7f3xfyxw8XozsUk+GShm/QP5PFsXfOHO408tpDtHohfeAuZQQyxuR84n9xnJ25cJh3vcZm7VjAY5GJB+TBtipInNtKNl6uLazHH20Yb6RZtKJ+EYutd11Z5DySfa1g6uObtuASFguYNEqVLGZEKBmShJhepdupR53jnXzGfL/XP/VRGyRexsjuBj8PcNr9jvA6iDEx6H0j0zbYyd2vzMwxbkxhAQLHHtRmMaWM6ns4X8o/E1eTMG+pjohurm79YBEaUdAGEnpVjYerCB101AVEw2QEAIYqEgLfBIZijkkdUJnLC8q683hffW5lzn4ZPpXzqDoikG4IRjOwqi7eWnjHwOOWvlYhrpYw0NSeicqU49/7CnFLHH6ZYnpaJx5UDhkGkuGSaeBanJf3E5ROiE6b7PDAuGjMSD9g9tPZdozgOdPcBZY56HTiWBTFVfhQmxuLnTEWPOO7QVlRHXBu8xYHf6r3NHWrLQijr0//Zr2BxHYyL4/3hinb0y9Eyn0EW7wWFwuUkJvxM1ZhBehog+Gq8Mp1Z2k+OWYC1ISLMFW6hrKb04XFEnub2vTDMtpLE+0G0lguqJj1w9x+ZAooLNcOgxnVtfMQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
