travis:
  secure:
    BINSTAR_TOKEN: 0QvT5BRSFjZuSFz1Nu3Q5MNrxlwhnbxDBoKc5gkKHfSHvS/RKJvSdEW284nzK03mDQNsCY/IRAJOLQjsoB5zoQkOduVQuw6u5RoqvuAGj9wMp2a1kj+xYzkdVuXT6jmCUAVxmXV6SU7nYX+FOqVMO4x60vsaMP21T/ySB24lPn0vbrwmTWaDk+4fTnAPz7FV2dVzgKlD60LzYaSXD20tXQg5HdkXqY+3NSUjkBX24H12WI9qRSZ0TddaJi68lbmSrhjggyRQJU857ocWYcYpgNxxKV0T8AWRtCN6RO8bhKj5NrzVyBjMIANlTg6qFMYWYNmFzPapSz3yaozuGjAz7J5vMxaaWCXkh3DC0NfgMMydpOpD1AaR4BXdpPMqQXxgTp8RFt/pty1iSGNUgIot5WgAnaVN7ItBRbEUCCK9Mxid31/PiY6Pg1gB/jfKJwrNzcS/wYsRBlGVxvYs51EHbZkwKkudV0BCJ876NSrgTfm/tELlyNEo8f+YWM8AC0XjzSLOUWi8LeoHG4qFUY15mlig4zCrB3f6S1+5djSDonRnAQRtwChC2I7ynBhKBB0GO14GDv0Gqfr29csW6NrMGLZceuqraTzLRWyLFOgJc3J4R+Vu7fIVXN4KpbeXpD4VIT1e4LP331mpFoxPjTQ3jTNyxpI622D2xso7dgTmttA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
